import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:intl/intl.dart';
import 'package:printing/printing.dart';

import '../core/app_strings.dart';
import '../core/sensor_manager.dart';
import '../core/pdf_report_service.dart';
import '../core/report_repository.dart';

/// Report data model
class ReportData {
  final String id;
  final String type;
  final DateTime createdAt;
  final Map<String, dynamic> data;

  ReportData({
    required this.id,
    required this.type,
    required this.createdAt,
    required this.data,
  });
}

/// Report Generator Page - Generate and preview reports
class ReportGeneratorPage extends StatefulWidget {
  final String reportType;
  final String reportTitle;

  const ReportGeneratorPage({
    super.key,
    required this.reportType,
    required this.reportTitle,
  });

  @override
  State<ReportGeneratorPage> createState() => _ReportGeneratorPageState();
}

class _ReportGeneratorPageState extends State<ReportGeneratorPage> {
  bool _isGenerating = false;
  ReportData? _generatedReport;

  @override
  void initState() {
    super.initState();
    _generateReport();
  }

  Future<void> _generateReport() async {
    setState(() => _isGenerating = true);

    // Simulate generation delay
    await Future.delayed(const Duration(seconds: 1));

    final manager = Provider.of<SensorManager>(context, listen: false);

    final data = <String, dynamic>{
      'totalEarnings': manager.totalEarnings,
      'uniqueHexCount': manager.uniqueHexCount,
      'bluetoothDensity': manager.bluetoothDensity,
      'currentDecibel': manager.decibel,
      'currentPressure': manager.pressure,
      'networkType': manager.networkType,
      'latency': manager.latency,
      'isSampling': manager.isSampling,
    };

    setState(() {
      _generatedReport = ReportData(
        id: DateTime.now().millisecondsSinceEpoch.toString(),
        type: widget.reportType,
        createdAt: DateTime.now(),
        data: data,
      );
      _isGenerating = false;
    });

    // Auto-save report to history
    if (_generatedReport != null) {
      await ReportRepository.saveReport(
        _generatedReport!,
        title: widget.reportTitle,
      );
    }
  }

  /// Generate and preview/share PDF report
  Future<void> _generatePdf() async {
    if (_generatedReport == null) return;

    final isZh = AppStrings.languageCode == 'zh';

    try {
      final pdfData = await PdfReportService.generatePdf(_generatedReport!);

      await Printing.layoutPdf(
        onLayout: (format) async => pdfData,
        name: 'SmartSensor_Report_${_generatedReport!.id}.pdf',
      );
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(
          content: Text(isZh ? 'PDF生成失败: $e' : 'PDF generation failed: $e'),
          backgroundColor: Colors.redAccent,
        ));
      }
    }
  }

  void _shareReport() {
    if (_generatedReport == null) return;

    final dateStr =
        DateFormat('yyyy-MM-dd HH:mm').format(_generatedReport!.createdAt);
    final isZh = AppStrings.languageCode == 'zh';

    String reportText;
    if (widget.reportType == 'weekly') {
      reportText = isZh
          ? '''📊 SmartSensor 周报告
生成时间: $dateStr

📈 数据统计
• 总积分: ${_generatedReport!.data['totalEarnings'].toStringAsFixed(1)} QBit
• 覆盖区域: ${_generatedReport!.data['uniqueHexCount']} 个六边形
• 蓝牙设备密度: ${_generatedReport!.data['bluetoothDensity']}

🌐 网络状态
• 网络类型: ${_generatedReport!.data['networkType']}
• 延迟: ${_generatedReport!.data['latency']}ms

🎯 感测状态: ${_generatedReport!.data['isSampling'] ? '运行中' : '已暂停'}

---
由 SmartSensor 生成
https://smartsensor.yourcompany.com'''
          : '''📊 SmartSensor Weekly Report
Generated: $dateStr

📈 Statistics
• Total Points: ${_generatedReport!.data['totalEarnings'].toStringAsFixed(1)} QBit
• Coverage Areas: ${_generatedReport!.data['uniqueHexCount']} hexes
• Bluetooth Density: ${_generatedReport!.data['bluetoothDensity']}

🌐 Network Status
• Network Type: ${_generatedReport!.data['networkType']}
• Latency: ${_generatedReport!.data['latency']}ms

🎯 Sensing Status: ${_generatedReport!.data['isSampling'] ? 'Active' : 'Paused'}

---
Generated by SmartSensor
https://smartsensor.yourcompany.com''';
    } else if (widget.reportType == 'noise') {
      reportText = isZh
          ? '''🔊 SmartSensor 噪音检测报告
生成时间: $dateStr

📊 当前读数
• 环境噪音: ${_generatedReport!.data['currentDecibel'].toStringAsFixed(1)} dB

📍 检测位置
• 通过 SmartSensor 应用测量

---
由 SmartSensor 生成
https://smartsensor.yourcompany.com'''
          : '''🔊 SmartSensor Noise Report
Generated: $dateStr

📊 Current Reading
• Ambient Noise: ${_generatedReport!.data['currentDecibel'].toStringAsFixed(1)} dB

📍 Detection Location
• Measured via SmartSensor app

---
Generated by SmartSensor
https://smartsensor.yourcompany.com''';
    } else if (widget.reportType == 'wifi') {
      reportText = isZh
          ? '''📶 SmartSensor WiFi分析报告
生成时间: $dateStr

🌐 网络状态
• 连接类型: ${_generatedReport!.data['networkType']}
• 网络延迟: ${_generatedReport!.data['latency']}ms

💡 建议
• 使用 WiFi 分析器扫描以获取详细的网络覆盖数据

---
由 SmartSensor 生成
https://smartsensor.yourcompany.com'''
          : '''📶 SmartSensor WiFi Analysis Report
Generated: $dateStr

🌐 Network Status
• Connection Type: ${_generatedReport!.data['networkType']}
• Network Latency: ${_generatedReport!.data['latency']}ms

💡 Recommendations
• Use WiFi Analyzer scan for detailed coverage data

---
Generated by SmartSensor
https://smartsensor.yourcompany.com''';
    } else {
      reportText = isZh
          ? '''📊 SmartSensor 检测报告
生成时间: $dateStr
类型: ${widget.reportTitle}

---
由 SmartSensor 生成'''
          : '''📊 SmartSensor Detection Report
Generated: $dateStr
Type: ${widget.reportTitle}

---
Generated by SmartSensor''';
    }

    SharePlus.instance.share(ShareParams(text: reportText));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF0D0D1A),
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        title: Text(widget.reportTitle),
        actions: [
          if (_generatedReport != null)
            IconButton(
              icon: const Icon(Icons.picture_as_pdf),
              tooltip:
                  AppStrings.languageCode == 'zh' ? '生成PDF' : 'Generate PDF',
              onPressed: _generatePdf,
            ),
          if (_generatedReport != null)
            IconButton(
              icon: const Icon(Icons.share),
              onPressed: _shareReport,
            ),
        ],
      ),
      body: _isGenerating
          ? const Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  CircularProgressIndicator(color: Colors.cyanAccent),
                  SizedBox(height: 16),
                  Text(
                    'Generating report...',
                    style: TextStyle(color: Colors.white54),
                  ),
                ],
              ),
            )
          : _generatedReport != null
              ? _buildReportContent()
              : const Center(
                  child: Text(
                    'Failed to generate report',
                    style: TextStyle(color: Colors.redAccent),
                  ),
                ),
    );
  }

  Widget _buildReportContent() {
    final dateStr =
        DateFormat('yyyy-MM-dd HH:mm').format(_generatedReport!.createdAt);
    final isZh = AppStrings.languageCode == 'zh';

    return SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Report Header
          Container(
            padding: const EdgeInsets.all(20),
            decoration: BoxDecoration(
              gradient: LinearGradient(
                colors: [
                  Colors.purpleAccent.withValues(alpha: 0.3),
                  Colors.cyanAccent.withValues(alpha: 0.1),
                ],
              ),
              borderRadius: BorderRadius.circular(20),
              border:
                  Border.all(color: Colors.purpleAccent.withValues(alpha: 0.5)),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    const Icon(Icons.assessment,
                        color: Colors.cyanAccent, size: 32),
                    const SizedBox(width: 12),
                    Expanded(
                      child: Text(
                        widget.reportTitle,
                        style: const TextStyle(
                          color: Colors.white,
                          fontSize: 20,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 8),
                Text(
                  '${isZh ? '生成时间' : 'Generated'}: $dateStr',
                  style: const TextStyle(color: Colors.white54, fontSize: 12),
                ),
              ],
            ),
          ),
          const SizedBox(height: 20),

          // Data Statistics
          _buildSectionCard(
            title: isZh ? '📈 数据统计' : '📈 Statistics',
            children: [
              _buildDataRow(
                isZh ? '总积分' : 'Total Points',
                '${_generatedReport!.data['totalEarnings'].toStringAsFixed(1)} QBit',
                Colors.amber,
              ),
              _buildDataRow(
                isZh ? '覆盖区域' : 'Coverage',
                '${_generatedReport!.data['uniqueHexCount']} ${isZh ? '个六边形' : 'hexes'}',
                Colors.greenAccent,
              ),
              _buildDataRow(
                isZh ? '蓝牙密度' : 'Bluetooth Density',
                '${_generatedReport!.data['bluetoothDensity']}',
                Colors.blueAccent,
              ),
            ],
          ),
          const SizedBox(height: 16),

          // Environment Data
          _buildSectionCard(
            title: isZh ? '🌡️ 环境数据' : '🌡️ Environment',
            children: [
              _buildDataRow(
                isZh ? '环境噪音' : 'Noise Level',
                '${_generatedReport!.data['currentDecibel'].toStringAsFixed(1)} dB',
                Colors.orangeAccent,
              ),
              _buildDataRow(
                isZh ? '大气压力' : 'Pressure',
                '${_generatedReport!.data['currentPressure'].toStringAsFixed(1)} hPa',
                Colors.cyanAccent,
              ),
            ],
          ),
          const SizedBox(height: 16),

          // Network Status
          _buildSectionCard(
            title: isZh ? '🌐 网络状态' : '🌐 Network',
            children: [
              _buildDataRow(
                isZh ? '网络类型' : 'Network Type',
                _generatedReport!.data['networkType'],
                Colors.purpleAccent,
              ),
              _buildDataRow(
                isZh ? '网络延迟' : 'Latency',
                '${_generatedReport!.data['latency']}ms',
                Colors.tealAccent,
              ),
            ],
          ),
          const SizedBox(height: 24),

          // Share Button
          SizedBox(
            width: double.infinity,
            child: ElevatedButton.icon(
              onPressed: _shareReport,
              icon: const Icon(Icons.share),
              label: Text(isZh ? '分享报告' : 'Share Report'),
              style: ElevatedButton.styleFrom(
                backgroundColor: Colors.cyanAccent,
                foregroundColor: Colors.black,
                padding: const EdgeInsets.symmetric(vertical: 16),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(16),
                ),
              ),
            ),
          ),
          const SizedBox(height: 100),
        ],
      ),
    );
  }

  Widget _buildSectionCard({
    required String title,
    required List<Widget> children,
  }) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: const Color(0xFF1E1E3F),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: Colors.white.withValues(alpha: 0.1)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: const TextStyle(
              color: Colors.white,
              fontSize: 16,
              fontWeight: FontWeight.bold,
            ),
          ),
          const SizedBox(height: 12),
          ...children,
        ],
      ),
    );
  }

  Widget _buildDataRow(String label, String value, Color color) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 6),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(label, style: const TextStyle(color: Colors.white54)),
          Text(
            value,
            style: TextStyle(
              color: color,
              fontWeight: FontWeight.bold,
            ),
          ),
        ],
      ),
    );
  }
}
